#!/usr/bin/env php

<?php

use Symfony\Component\Console\Application;

require __DIR__ . '/bootstrap.php';

$app = new Application();

$app->add(new \Code\Command\TeamsCommand());
$app->add(new \Code\Command\MatchesCommand());

$app->run();
